version: 0.2

env:
  variables:
    PYLINT_THRESHOLD: "9.0"

phases:
  install:
    commands:
    - yum update -y
    - yum install -y python3-pip
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install django djangorestframework pylint
    - wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
    - unzip -q sonar-scanner-cli-5.0.1.3006-linux.zip
    - java -version
    - export JAVA_HOME=$(pwd)/sonar-scanner-5.0.1.3006-linux/jre
    - java -version
    - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin
    - sonar-scanner --version

  pre_build:
    commands:
    - pip install -r requirements.txt
    # Automatically fix some of the issues detected by pylint
    - pylint --exit-zero --output-format=text api booking customer room_manager room_slot | tee pylint_report.txt
    - PYLINT_SCORE=$(awk '/Your code has been rated at/{print $7}' pylint_report.txt | cut -d'/' -f1)
    - echo "Pylint Score ${PYLINT_SCORE}"
    # Fail the build if PYLINT_SCORE is below the threshold
    - |
      if (( $(echo "$PYLINT_SCORE < $PYLINT_THRESHOLD" | bc -l) )); then
        echo "Pylint score is below the threshold of $PYLINT_THRESHOLD"
        exit 1
      fi

  build:
    commands:
    - |
      # Use --noinput to avoid prompting for input
      python manage.py test --noinput
    # Performing the SonarQube Analysis
    - sonar-scanner -Dsonar.organization=x23189851 -Dsonar.projectKey=Himashreems_x23189851-Devsecops -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.python.pylint.reportPaths=pylint_report.txt

artifacts:
  files:
  - '**/*'
